### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by SiCole180421** [MisterZtr/PixelOS_gsi#58]
Thanks for the new update, NFC and BT audio now working on s24 ultra but the others, main ones too don't work

Incall audio
Facebook crashing on launch 
Youtube crashing on launch

I have logs for all three 

[logcat_05-12-2024_16-20-53.txt](https://github.com/MisterZtr/PixelOS_gsi/files/15286794/logcat_05-12-2024_16-20-53.txt)
Phone ^

[logcat_05-12-2024_16-21-44.txt](https://github.com/MisterZtr/PixelOS_gsi/files/15286796/logcat_05-12-2024_16-21-44.txt)
Facebook^

[logcat_05-12-2024_16-22-38.txt](https://github.com/MisterZtr/PixelOS_gsi/files/15286798/logcat_05-12-2024_16-22-38.txt)
Youtube^

Hope these can be resolved, arguably the best gsi out there right now too

**Comment by MisterZtr** [comment]
One person with Samsung was helped by updating to the latest version of the official ROM to make the qpr2 GSIs work much better

**Comment by flexynos** [comment]
There are a lot of serious changes in QPR2, try updating the stock firmware and check if Samsung has updated the kernel or the vendor. On S22 freezing problems were solved by a simple update

**Comment by SiCole180421** [comment]
Yeah I did the update last night and it does actually seem samsung has updated the vendor partition. Will reinstall tonight and see if those issues persist or not

**Comment by SiCole180421** [comment]
same issues unfortunately, the new samsung update didnt fix it
incall audio works on aosp though

**Comment by SiCole180421** [comment]
i was just comparing both PixelOS files directly with AOSP GSI files too see if theres an obvious change as to why incall audio works on AOSP GSI but i cant find anything different at all, unless im looking in the wrong places

**Comment by SiCole180421** [comment]
If possible, could you sync aosp instead of TD? Every GSI I've tried now so far that's synced with TD has all those issues. AOSP based GSIs are all working fine
